#!/usr/bin/env bash
set -e

JOB=$1

# build
function build(){
  docker run \
    --rm \
    -v `pwd`:/haya/contracts \
    -w /haya/contracts \
    -ti mixbytes/haya:devel \
    ./cicd/build.sh
}

# pack
function pack(){
  docker run \
    --rm \
    -v `pwd`:/haya/contracts \
    -w /haya/contracts \
    -ti mixbytes/haya:devel \
    ./cicd/pack.sh
}

function test(){
# test
  docker run \
    --rm \
    -v `pwd`:/haya/contracts \
    -w /haya/contracts \
    -ti mixbytes/haya:devel \
    /haya/contracts/build/tests/unit_test
}

$JOB
